version: '3.4'

services:
  redis:
    container_name: redis
    image: redis/redis-stack-server
    ports:
      - '6379:6379'

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.3
    links:
      - redis
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_DEFAULT_APP_MODE=development
    volumes:
      - ./dist:/var/lib/grafana/plugins/redis-datasource
      # - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana
