// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');

// This process will use the same config that `yarn test` is using
const grafanaJestConfig = standard.jestConfig('');
module.exports = {
  ...grafanaJestConfig,
  coveragePathIgnorePatterns: ['node_modules', 'src/tests'].concat(
    grafanaJestConfig.coveragePathIgnorePatterns ? grafanaJestConfig.coveragePathIgnorePatterns : []
  ),
};
