services:
  redis:
    image: redis/redis-stack-server
    ports:
      - '63790:6379'
    volumes:
      - '../data:/data/:rw'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 5s
