name: Integration

on:
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build and test frontend
        run: yarn build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Check for backend
        id: check-for-backend
        run: |
          if [ -f "Magefile.go" ]
          then
            echo "::set-output name=has-backend::true"
          fi

      - name: Setup Go environment
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: "1.19"

      - name: Test backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: cover

      - name: Build backend
        if: steps.check-for-backend.outputs.has-backend == 'true'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: buildAll

      - name: Run integration tests
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: integration

      - name: Run cluster integration tests
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: cluster
