name: Integration

on: [pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Build backend
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: buildAll

      - name: Run integration tests
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: integration
